services:
  db-mercado:
    image: postgres:18
    container_name: pg-mercado-container
    environment:
      POSTGRES_PASSWORD: senha123
      
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
     
      - ./.pgdata:/var/lib/postgresql:Z
    
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql